apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-indexer-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
data:
  wazuh.indexer.yml: |
    network.host: 0.0.0.0
    node.name: wazuh.indexer
    bootstrap.system_call_filter: false
    discovery.type: single-node
    compatibility.override_main_response_version: true

    plugins.security.ssl.transport.pemcert_filepath: certs/wazuh.indexer.pem
    plugins.security.ssl.transport.pemkey_filepath: certs/wazuh.indexer.key
    plugins.security.ssl.transport.pemtrustedcas_filepath: certs/root-ca.pem
    plugins.security.ssl.transport.enforce_hostname_verification: false
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: certs/wazuh.indexer.pem
    plugins.security.ssl.http.pemkey_filepath: certs/wazuh.indexer.key
    plugins.security.ssl.http.pemtrustedcas_filepath: certs/root-ca.pem
    plugins.security.allow_unsafe_democertificates: false
    plugins.security.allow_default_init_securityindex: true
    plugins.security.authcz.admin_dn:
      - "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
    plugins.security.nodes_dn:
      - "CN=wazuh-indexer,OU=Wazuh,O=Wazuh,L=California,C=US"
    plugins.security.audit.type: internal_opensearch
    plugins.security.enable_snapshot_restore_privilege: true
    plugins.security.check_snapshot_restore_write_privileges: true
    cluster.routing.allocation.disk.threshold_enabled: false
