apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: indexer
  ports:
    - name: http
      port: 9200
      targetPort: http
      protocol: TCP
