apiVersion: v1
kind: Secret
metadata:
  name: wazuh-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.wazuh.adminPassword | quote }}
