apiVersion: v1
kind: Service
metadata:
  name: wazuh-manager-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
