replicaCount: 1

resources:
  limits:
    cpu: "2000m"
    memory: "4Gi"
  requests:
    cpu: "1000m"
    memory: "2Gi"

storage:
  size: 100Gi
  storageClass: "standard"

agentService:
  type: LoadBalancer

wazuh:
  alertLevel: 3
