manager:
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"
  storage:
    size: 20Gi
    storageClass: "standard"

indexer:
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"
  storage:
    size: 20Gi
    storageClass: "standard"
  javaOpts: "-Xms512m -Xmx512m"

dashboard:
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

agentService:
  type: LoadBalancer
